import permission from "./modules/permission";
import settings from "./modules/settings";

const getters = {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  panelsData: state => state.app.panelsData,
  panelsRefresh: state => state.app.panelsRefresh,
  hideChartIdList: state => state.app.hideChartId,
  isFullScreen: state => state.app.isFullScreen,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  roles: state => state.user.roles,
  userId: state => state.user.userId,
  domainList: state => state.user.domainList,
  corporationName: state => state.user.corporationName,
  permission_routes: state => state.permission.routes,
  permissions: state => state.user.permissions,
  talentPoolPermission: state => state.talentPool.talentPoolPermission,
  defaultOpeneds: state => state.settings.defaultOpeneds,
  keepAliveList: state => state.settings.keepAliveList,
  shiftName: state=>state.settings.shiftName,
  caseTypeList: state=>state.caseInformation.caseTypeList,
  toDoTaskCaseId: state=>state.caseInformation.toDoTaskCaseId,
  toDoTaskId: state=>state.caseInformation.toDoTaskId,
  toDoTaskName: state=>state.caseInformation.toDoTaskName,
  total: state=>state.caseInformation.total,
  flag: state=>state.caseInformation.flag,
  workTimeStatus: state=>state.caseInformation.workTimeStatus,
  tmCaseTypeList:state=>state.caseInformation.tmCaseTypeList,
  tmCaseTypeIdList:state=>state.caseInformation.tmCaseTypeIdList,
  patentCaseTypeList:state=>state.caseInformation.patentCaseTypeList,
  patentCaseTypeIdList:state=>state.caseInformation.patentCaseTypeIdList,
  userList:state=>state.caseInformation.userList,
  allUserList:state=>state.caseInformation.allUserList,
  contactLanguage:state=>state.caseInformation.contactLanguage,
  progressList: state=>state.caseInformation.progressList,
  jyList: state=>state.caseInformation.jyList,
}
export default getters
