const billAction = {
  BILL_CREATE: 'BILL_CREATE',
  BILL_EDIT: 'BILL_EDIT',
  BILL_DELETE: 'BILL_DELETE',
  BILL_EDIT_REMARK: 'BILL_EDIT_REMARK',
  BILL_CREATE_INVOICE: 'BILL_CREATE_INVOICE',
  BILL_SEARCH: 'BILL_SEARCH',
  BILL_CLEAR_SEARCH: 'BILL_CLEAR_SEARCH',
  BILL_SUBMIT: 'BILL_SUBMIT',
  BILL_HEADMAN_AUDIT: 'BILL_HEADMAN_AUDIT',
  BILL_JOB_AUDIT: 'BILL_JOB_AUDIT',
  BILL_AUDIT: 'BILL_AUDIT',
  BILL_UNDERTAKE: 'BILL_UNDERTAKE',
  BILL_RECONFIRM: 'BILL_RECONFIRM',
  BILL_EDIT_DATE: 'BILL_EDIT_DATE',
  BILL_SUMBILLNO: 'BILL_SUMBILLNO',
  BILL_BALANCE: 'BILL_BALANCE',
  BILL_REBOOK: 'BILL_REBOOK',
  BILL_BADBILL: 'BILL_BADBILL',
  BILL_OUTBILL: 'BILL_OUTBILL',
  BILL_EXPORT_MODEL: 'BILL_EXPORT_MODEL',
  BILL_COLLECTION: 'BILL_COLLECTION',
  BILL_DOWNLOAD: 'BILL_DOWNLOAD'
}

export default billAction
