const borrowAction = {
  BORROW_CREATE: 'BORROW_CREATE',
  BORROW_EDIT: 'BORROW_EDIT',
  BORROW_DELETE: 'BORROW_DELETE',
  BORROW_SUBMIT: 'BORROW_SUBMIT',
  BORROW_AUDIT: 'BORROW_AUDIT',
  BORROW_PAY: 'BORROW_PAY',
  BORROW_REPAY: 'BORROW_REPAY',
  BORROW_REBOOK: 'BORROW_REBOOK',
  BORROW_SEARCH: 'BORROW_SEARCH',
  BORROW_CLEAR_SEARCH: 'BORROW_CLEAR_SEARCH'
}

export default borrowAction
