const collectionAction = {
  COLLECTION_SEARCH: 'COLLECTION_SEARCH',
  COLLECTION_CLEAR_SEARCH: 'COLLECTION_CLEAR_SEARCH',
  COLLECTION_CREATE: 'COLLECTION_CREATE',
  COLLECTION_EDIT: 'COLLECTION_EDIT',
  COLLECTION_DELETE: 'COLLECTION_DELETE',
  COLLECTION_SUBMIT: 'COLLECTION_SUBMIT',
  COLLECTION_CHECK: 'COLLECTION_CHECK',
  COLLECTION_REBOOK: 'COLLECTION_REBOOK'
}

export default collectionAction
