const exchangeAction = {
  EXCHANGE_RATE_CREATE: 'EXCHANGE_RATE_CREATE',
  EXCHANGE_RATE_EDIT: 'EXCHANGE_RATE_EDIT',
  EXCHANGE_RATE_SEARCH: 'EXCHANGE_RATE_SEARCH',
}
export default exchangeAction
