const insideBillAction = {
  INSIDE_BILL_CREATE: 'INSIDE_BILL_CREATE',
  INSIDE_BILL_EDIT: 'INSIDE_BILL_EDIT',
  INSIDE_BILL_AUDIT: 'INSIDE_BILL_AUDIT',
  INSIDE_BILL_SEARCH: 'INSIDE_BILL_SEARCH',
  INSIDE_BILL_CLEAR_SEARCH: 'INSIDE_BILL_CLEAR_SEARCH'

}

export default insideBillAction
