const invoiceBorrowAction = {
  INVOICE_BORROW_CREATE: 'INVOICE_BORROW_CREATE',
  INVOICE_BORROW_EDIT: 'INVOICE_BORROW_EDIT',
  INVOICE_BORROW_DELETE: 'INVOICE_BORROW_DELETE',
  INVOICE_BORROW_SUBMIT: 'INVOICE_BORROW_SUBMIT',
  INVOICE_BORROW_AUDIT: 'INVOICE_BORROW_AUDIT',
  INVOICE_BORROW_DEBTOR: 'INVOICE_BORROW_DEBTOR',
  INVOICE_BORROW_REBOOK: 'INVOICE_BORROW_REBOOK',
  INVOICE_BORROW_SEARCH: 'INVOICE_BORROW_SEARCH',
  INVOICE_BORROW_CLEAR_SEARCH: 'INVOICE_BORROW_CLEAR_SEARCH',
  INVOICE_TIME_DELAY: 'INVOICE_TIME_DELAY'
}

export default invoiceBorrowAction
