const invoiceLibraryAction = {
  INVOICE_LIBRARY_CREATE: 'INVOICE_LIBRARY_CREATE',
  INVOICE_LIBRARY_BATCH_PROCESS: 'INVOICE_LIBRARY_BATCH_PROCESS',
  INVOICE_LIBRARY_BATCH_PEOPLE: 'INVOICE_LIBRARY_BATCH_PEOPLE',
  INVOICE_LIBRARY_ZEROING: 'INVOICE_LIBRARY_ZEROING',
  INVOICE_LIBRARY_EDIT: 'INVOICE_LIBRARY_EDIT',
  INVOICE_LIBRARY_DELETE: 'INVOICE_LIBRARY_DELETE',
  INVOICE_LIBRARY_SEARCH: 'INVOICE_LIBRARY_SEARCH',
  INVOICE_LIBRARY_CLEAR_SEARCH: 'INVOICE_LIBRARY_CLEAR_SEARCH',
  INVOICE_LIBRARY_WITHDRAW: 'INVOICE_LIBRARY_WITHDRAW'
}

export default invoiceLibraryAction
