const invoiceOpenerAction = {
  INVOICE_OPENER_CREATE: 'INVOICE_OPENER_CREATE',
  INVOICE_OPENER_EDIT: 'INVOICE_OPENER_EDIT',
  INVOICE_OPENER_DELETE: 'INVOICE_OPENER_DELETE',
  INVOICE_OPENER_SUBMIT: 'INVOICE_OPENER_SUBMIT',
  INVOICE_OPENER_AUDIT: 'INVOICE_OPENER_AUDIT',
  INVOICE_OPENER: 'INVOICE_OPENER',
  INVOICE_OPENER_REBOOK: 'INVOICE_OPENER_REBOOK',
  INVOICE_OPENER_SEARCH: 'INVOICE_OPENER_SEARCH',
  INVOICE_OPENER_CLEAR_SEARCH: 'INVOICE_OPENER_CLEAR_SEARCH',
  INVOICE_OPENER_DATE: 'INVOICE_OPENER_DATE',
  INVOICE_OPENER_TAX_AMOUNT: 'INVOICE_OPENER_TAX_AMOUNT',
  UPLOAD_INVOICE: 'UPLOAD_INVOICE',
}

export default invoiceOpenerAction
