const outPriceAction = {
  OUTPRICE_SEARCH: 'OUTPRICE_SEARCH',
  OUTPRICE_CREATE: 'OUTPRICE_CREATE',
  OUTPRICE_EDIT: 'OUTPRICE_EDIT',
  OUTPRICE_ZY: 'OUTPRICE_ZY',
  OUTPRICE_MDL: 'OUTPRICE_MDL',
  OUTPRICE_EXPORT_MODEL: 'OUTPRICE_EXPORT_MODEL',
  OUTPRICE_WAIBI: 'OUTPRICE_WAIBI'
}

export default outPriceAction
