const outBillAction = {
  OUTBILL_SEARCH: 'OUTBILL_SEARCH',
  OUTBILL_CREATE: 'OUTBILL_CREATE',
  OUTBILL_SUBMIT: 'OUTBILL_SUBMIT',
  OUTBILL_FIRSTAUDIT: 'OUTBILL_FIRSTAUDIT',
  OUTBILL_PAY: 'OUTBILL_PAY',
  OUTBILL_SECONDAUDIT: 'OUTBILL_SECONDAUDIT',
  OUTBILL_BATCH_PAY: 'OUTBILL_BATCH_PAY',
  OUTBILL_EDIT: 'OUTBILL_EDIT',
  OUTBILL_DEL: 'OUTBILL_DEL',
  OUTBILL_CLEAR_SEARCH: 'OUTBILL_CLEAR_SEARCH',
  OUTBILL_PL_EDIT: 'OUTBILL_PL_EDIT',
  OUTBILL_EXPORT_MODEL: 'OUTBILL_EXPORT_MODEL',
  OUTBILL_CREATE_FEE: 'OUTBILL_CREATE_FEE',
  OUTBILL_REBOOK: 'OUTBILL_REBOOK',
  UPLOAD_BILL: 'UPLOAD_BILL',
  DOWNLOAD_BILL: 'DOWNLOAD_BILL',
  OUTBILL_PATCHIMPORT: 'OUTBILL_PATCHIMPORT',
}

export default outBillAction
