const patentAction = {
  PATENT_EDIT: 'PATENT_EDIT',
  PATENT_SEARCH: 'PATENT_SEARCH',
  PATENT_CREATE: 'PATENT_CREATE',
  PATENT_CLEAR_SEARCH: 'PATENT_CLEAR_SEARCH',
  PATENT_NET_PAY: 'PATENT_NET_PAY',
  PATENT_FINANCE_PAY: 'PATENT_FINANCE_PAY',
  PATENT_RECEIPT_INPUT: 'PATENT_RECEIPT_INPUT',
  PATENT_CHARGE_EXCHANGE: 'PATENT_CHARGE_EXCHANGE',
  PATENT_MERGE: 'PATENT_MERGE'
}

export default patentAction
