const reportManageAction = {
  REPORT_MANAGE_CREATE: 'REPORT_MANAGE_CREATE',
  REPORT_MANAGE_EDIT: 'REPORT_MANAGE_EDIT',
  REPORT_MANAGE_DELETE: 'REPORT_MANAGE_DELETE',
  REPORT_MANAGE_SEARCH: 'REPORT_MANAGE_SEARCH',
}

export default reportManageAction
