const reportAccountAction = {
  REPORT_ACCOUNT_CREATE: 'REPORT_ACCOUNT_CREATE',
  REPORT_ACCOUNT_EDIT: 'REPORT_ACCOUNT_EDIT',
  REPORT_ACCOUNT_DELETE: 'REPORT_ACCOUNT_DELETE',
  REPORT_ACCOUNT_SEARCH: 'REPORT_ACCOUNT_SEARCH'
}

export default reportAccountAction
