const reportAction = {
  REPORT_CREATE: 'REPORT_CREATE',
  REPORT_EDIT: 'REPORT_EDIT',
  REPORT_DELETE: 'REPORT_DELETE',
  REPORT_SEARCH: 'REPORT_SEARCH',
  REPORT_EXPORT: 'REPORT_EXPORT',
  REPORT_LOCK: 'REPORT_LOCK'
}

export default reportAction
