const statementAction = {
  STATEMENT_SET_CREDIT: 'STATEMENT_SET_CREDIT',
  STATEMENT_SET_STATEMENT: 'STATEMENT_SET_STATEMENT',
  STATEMENT_SEARCH: 'STATEMENT_SEARCH',
  STATEMENT_EDIT_CREDIT: 'STATEMENT_EDIT_CREDIT',
  STATEMENT_EDIT_STATEMENT: 'STATEMENT_EDIT_STATEMENT',
  STATEMENT_EXPORT: 'STATEMENT_EXPORT'
}
export default statementAction
